/* NEXEN workspace demo: one shell, three mock workspaces. All content is DEMO DATA. Nothing here is live, connected or verified. */
(function () {
  const F = (name, cat, status, owner, mod, size, prev) => ({ name, cat, status, owner, mod, size, prev });

  const construction = {
    id: "construction", route: "construction", icon: "🏗️", name: "Construction", workspace: "Riverside Tower Project", short: "Riverside Tower",
    tint: "#ffb000", user: { name: "Priya Nair", role: "Project Manager", initials: "PN" },
    blurb: "Project operations, RFIs, change orders, schedules, subcontractors and field activity.",
    summaryLine: "Here's what needs attention across Riverside Tower today.",
    kpis: [["82%", "Project Complete", "On schedule"], ["3", "Open RFIs", "1 overdue"], ["$1.24M", "Remaining Budget", "Change order pending"], ["7", "Active Subcontractors", "2 on site today"]],
    priority: [["HIGH", "Change Order #017 requires approval", "+$38,400 impact", 2], ["HIGH", "RFI #042 unanswered for 48 hours", "Electrical routing conflict", 1], ["MEDIUM", "Safety inspection due tomorrow", "Confirmation needed", 3], ["LOW", "Concrete delivery confirmation pending", "Supplier has not replied", 7]],
    recommend: { title: "Review Change Order #017 first", text: "It adds $38,400 and is over the $25,000 approval limit. RFI #042 can be answered right after, since the architect is available this afternoon.", file: 2 },
    files: [
      F("Riverside_Project_Schedule.pdf", "Schedule", "Approved", "Priya Nair", "Oct 7, 2026", "2.4 MB", { head: "Project Schedule", sub: "Riverside Tower · Revision 14", fields: [["Complete", "82%"], ["Next milestone", "Level 8 drywall start"], ["Schedule float", "2 days"]], blocks: [["Critical path", "Level 8 MEP rough-in, then drywall, then paint. RFI #042 sits on the critical path."], ["Look ahead", "Concrete pour on Level 9 is planned for October 16."]], summary: "The schedule is on track. Level 8 drywall slips if RFI #042 stays open past Friday.", related: [1, 7] }),
      F("RFI-042_Electrical_Conflict.docx", "RFIs", "Flagged", "Marco Reyes", "Oct 5, 2026", "86 KB", { head: "RFI #042", sub: "Electrical Routing Conflict", fields: [["Status", "Awaiting Response"], ["Submitted", "October 5, 2026"], ["Assigned", "Project Engineer"]], blocks: [["Issue", "Electrical conduit conflicts with revised HVAC routing on Level 8."], ["Requested action", "Provide revised routing direction prior to drywall installation."]], summary: "Unanswered for 48 hours. The architect's reply is needed before drywall starts on Level 8.", related: [5, 0], activity: ["RFI #042 assigned to Project Engineer", "Reminder sent to the architect (Oct 6)"] }),
      F("Change_Order_017.xlsx", "Change Orders", "Needs Review", "Priya Nair", "Oct 7, 2026", "112 KB", { head: "Change Order #017", sub: "HVAC reroute and fire-stopping, Level 8", fields: [["Total impact", "+$38,400"], ["Approval limit", "$25,000"], ["Needs", "Executive sign-off"]], table: { cols: ["Item", "Description", "Amount"], rows: [["1", "HVAC reroute, Level 8", "$14,200"], ["2", "Electrical rework to match", "$11,800"], ["3", "Fire-stopping at new penetrations", "$7,600"], ["4", "Overhead and fees", "$4,800"], ["", "Total", "$38,400"]] }, summary: "The total is above the approval limit and links to RFI #042. Approve before the electrical crew remobilizes.", related: [1, 5] }),
      F("Site_Safety_Report.pdf", "Safety", "Pending", "Dana Okafor", "Oct 6, 2026", "1.1 MB", { head: "Site Safety Report", sub: "Week 41", fields: [["Incidents", "0"], ["Near misses", "2"], ["Inspection", "Tomorrow 9:00"]], blocks: [["Notes", "Two near misses involved unsecured materials near the hoist. Corrected on the same day."], ["Open item", "Confirm tomorrow's inspection with the site superintendent."]], summary: "Clean week. The inspection still needs a confirmed time from the site team.", related: [0] }),
      F("Subcontractor_Invoice_October.pdf", "Invoices", "Needs Review", "Accounts Payable", "Oct 7, 2026", "640 KB", { head: "Invoice #8921", sub: "Delta Electric · October", fields: [["Amount", "$41,300"], ["Due", "October 9, 2026"], ["Contract match", "Yes"]], blocks: [["Line items", "Rough-in labor $29,800 and materials $11,500. Both match contract rates."]], summary: "The invoice matches the contract and is due in two days. Approval is the only step left.", related: [2] }),
      F("Blueprint_Revision_C3.pdf", "Drawings", "Updated", "Hale Architects", "Oct 6, 2026", "18.7 MB", { head: "Blueprint Revision C3", sub: "Level 8 · Mechanical and electrical", fields: [["Revision", "C3"], ["Sheets", "14"], ["Supersedes", "C2"]], blocks: [["What changed", "The HVAC chase moved 18 inches east. This is the cause of the conduit conflict in RFI #042."]], summary: "Revision C3 moved the HVAC chase and created the conflict in RFI #042.", related: [1] }),
      F("Weekly_Project_Update.docx", "Reports", "Approved", "Priya Nair", "Oct 4, 2026", "210 KB", { head: "Weekly Project Update", sub: "Week 40", fields: [["Complete", "80%"], ["Budget used", "71%"], ["Safety", "No incidents"]], blocks: [["Highlights", "Level 7 slab complete. Level 8 MEP rough-in 60 percent done."]], summary: "Last week closed two points ahead of plan on progress.", related: [0] }),
      F("Concrete_Delivery_Schedule.xlsx", "Logistics", "Pending", "Site Logistics", "Oct 7, 2026", "74 KB", { head: "Concrete Delivery Schedule", sub: "Level 9 pour", fields: [["Pour date", "Oct 16"], ["Volume", "180 cubic yards"], ["Supplier", "Granite Ready-Mix"]], table: { cols: ["Truck", "Window", "Status"], rows: [["1 to 6", "6:00 to 8:00", "Confirmed"], ["7 to 12", "8:00 to 10:30", "Pending"], ["13 to 18", "10:30 to 1:00", "Pending"]] }, summary: "Half of the delivery windows are still waiting on the supplier.", related: [0] })
    ],
    workers: [["Schedule Monitor", "Watches float and the critical path", "Watching"], ["Invoice Reviewer", "Matches invoices to contracts", "Processing"], ["Document Intake", "Files and tags incoming drawings", "Idle"], ["RFI Tracker", "Tracks due dates and owners", "Watching"], ["Daily Site Summary", "Builds the end-of-day report", "Idle"]],
    flows: [["RFI follow-up", "Reminds owners and escalates after 48 hours", 72], ["Invoice match", "Checks each invoice against the contract", 90], ["Drawing intake", "Tags new revisions and alerts affected trades", 55]],
    activity: [["MARVIN flagged Change Order #017", "10 min ago"], ["Blueprint Revision C3 uploaded", "1 h ago"], ["Invoice #8921 reviewed", "2 h ago"], ["RFI #042 assigned to Project Engineer", "Mon"], ["Daily site report processed", "Mon"]],
    tasks: [["Approve or reject Change Order #017", "Today", 2], ["Call the architect about RFI #042", "Today", 1], ["Confirm the safety inspection time", "Tomorrow", 3], ["Confirm concrete trucks 7 to 18", "Thu", 7]],
    chips: [["attention", "What needs my attention today?"], ["holding", "What's holding up Riverside Tower?"], ["rfi", "Summarize RFI #042."], ["invoices", "Which invoices need approval?"]],
    marvin: {
      attention: ["Good morning. Three items need your attention at Riverside Tower. Change Order 017 requires approval and adds $38,400 to project cost. RFI 042 has been unanswered for 48 hours and may affect electrical installation on Level 8. Tomorrow's safety inspection still requires confirmation. I recommend reviewing Change Order 017 first.", [2, 1, 3]],
      holding: ["Two things are holding up the project. RFI 042 blocks drywall on Level 8, and Change Order 017 has to be approved before the electrical crew can remobilize. Concrete delivery windows for the Level 9 pour are also half confirmed.", [1, 2, 7]],
      rfi: ["RFI 042 reports that electrical conduit conflicts with the revised HVAC routing on Level 8. It was submitted October 5th and is assigned to the project engineer. The requested action is revised routing direction before drywall installation. It is 48 hours overdue.", [1, 5]],
      invoices: ["One invoice needs approval. Invoice 8921 from Delta Electric is for $41,300, matches the contract, and is due October 9th. I can queue the approval for your review.", [4]]
    }
  };

  const corporate = {
    id: "corporate", route: "corporate", icon: "🏢", name: "Corporate", workspace: "Northstar Operations", short: "Northstar Operations",
    tint: "#3b8bff", user: { name: "Elena Ruiz", role: "Chief of Staff", initials: "ER" },
    blurb: "Teams, documents, meetings, budgets, vendors, projects and executive operations.",
    summaryLine: "Here's what needs executive attention across Northstar Operations today.",
    kpis: [["$4.8M", "Q3 Revenue", "3.1% above plan"], ["12", "Active Projects", "2 at risk"], ["91%", "Tasks On Track", "Up 2 points"], ["4", "Items Awaiting Approval", "1 needs a signature"]],
    meeting: {
      title: "Leadership Meeting", when: "Today 3:00 PM", starts: "Starts in 2 h 15 min", room: "Boardroom + video call",
      attendees: [["Elena Ruiz", "Chief of Staff"], ["Sam Whitaker", "FP&A"], ["Jordan Blake", "COO"], ["Priya Shah", "Sales"], ["Dev Okafor", "People Ops"]],
      agenda: [["3:00", "Q3 results", "Elena"], ["3:15", "FY2027 forecast variance", "Sam"], ["3:35", "Vendor agreement renewal", "Jordan"], ["3:50", "Pipeline: 3 stalled deals", "Priya"], ["4:00", "Decisions and actions", "All"]],
      talking: ["Lead with Q3 revenue of $4.8M, 3.1% above plan.", "The forecast is 6% over target. Cloud hosting, contractors and marketing software drive it.", "The vendor agreement auto-renews at +9% unless notice goes out by October 19th.", "Three deals worth $410k have been idle for 14 days."],
      spoken: "Here is your leadership meeting brief. Lead with Q3 revenue of 4.8 million dollars, three point one percent above plan. The forecast is six percent over target, driven by cloud hosting, contractors and marketing software. The vendor agreement auto-renews at nine percent more unless notice goes out by October nineteenth. Three deals worth four hundred ten thousand dollars have been idle for two weeks. Expect decisions on the vendor renewal and the forecast cuts.",
      preread: [0, 1, 3, 5],
      live: [["Elena", "Let's start with Q3. Revenue came in at 4.8 million, up three point one percent on plan."], ["Sam", "The FY2027 forecast is six percent over target. Cloud hosting, contractors and marketing software drive most of it."], ["Jordan", "The Brightloop agreement renews at nine percent more. I would rather negotiate than auto-renew."], ["Elena", "Agreed. Jordan, send notice by the nineteenth and ask for a flat renewal."], ["Priya", "Three deals are stalled, about 410 thousand. I will re-engage them this week."], ["Sam", "I will cut 300 thousand of contractor spend and bring a revised forecast on Friday."]],
      captured: [[2, "DECISION", "Negotiate the vendor renewal instead of auto-renewing"], [3, "ACTION", "Jordan: send vendor notice by Oct 19"], [4, "ACTION", "Priya: re-engage 3 stalled deals this week"], [5, "ACTION", "Sam: revised forecast with a $300k contractor cut by Friday"]],
      summary: "One decision and three actions. The vendor renewal will be negotiated, not auto-renewed. Jordan sends notice by October 19th, Priya re-engages the three stalled deals this week, and Sam brings a revised forecast on Friday."
    },
    priority: [["HIGH", "Vendor agreement requires signature", "Renews in 12 days", 3], ["HIGH", "Q4 forecast variance detected", "6% over target", 1], ["MEDIUM", "Executive meeting briefing due", "Today 3:00 PM", 2, "meeting"], ["LOW", "Three onboarding documents incomplete", "New hires this week", 4]],
    recommend: { title: "Sign the vendor agreement, then review the forecast", text: "The agreement renews at a 9% higher rate unless notice goes out this week. The forecast variance traces to three budget lines.", file: 3 },
    files: [
      F("Q3_Executive_Review.pptx", "Executive", "Needs Review", "Elena Ruiz", "Oct 7, 2026", "8.2 MB", { head: "Q3 Executive Review", sub: "12 slides", fields: [["Revenue", "$4.8M"], ["Vs plan", "+3.1%"], ["Presenter", "CEO"]], slides: ["Q3 revenue: $4.8M, 3.1% above plan", "12 active projects, 91% of tasks on track", "Risks: forecast variance and vendor renewal"], summary: "The deck is ready for review. Two risks are called out: the forecast variance and the vendor renewal.", related: [1, 3] }),
      F("FY2027_Budget_Forecast.xlsx", "Finance", "Flagged", "Sam Whitaker", "Oct 7, 2026", "420 KB", { head: "FY2027 Budget Forecast", sub: "Variance by line", fields: [["Forecast", "$12.9M"], ["Target", "$12.2M"], ["Variance", "+6%"]], table: { cols: ["Line", "Target", "Forecast"], rows: [["Cloud hosting", "$1.8M", "$2.1M"], ["Contractors", "$2.4M", "$2.7M"], ["Marketing software", "$0.4M", "$0.5M"], ["All other lines", "$7.6M", "$7.6M"]] }, summary: "The overage comes from three lines: cloud hosting, contractors and marketing software.", related: [0, 7] }),
      F("Leadership_Meeting_Notes.docx", "Meetings", "Updated", "Elena Ruiz", "Oct 6, 2026", "64 KB", { head: "Leadership Meeting Notes", sub: "Tuesday sync", fields: [["Attendees", "7"], ["Action items", "6"], ["Overdue", "2"]], blocks: [["Decisions", "Hold two open roles until Q1. Move the partner summit to January."], ["Open actions", "Budget cuts proposal. Vendor renewal decision."]], summary: "Six actions came out of the meeting. Two are overdue and both relate to budget and vendors.", related: [1, 3] }),
      F("Vendor_Agreement.pdf", "Legal", "Pending", "Procurement", "Oct 3, 2026", "1.6 MB", { head: "Vendor Agreement", sub: "Brightloop Cloud · Renewal", fields: [["Term", "12 months"], ["Increase", "+9%"], ["Notice deadline", "Oct 19"]], blocks: [["Signature", "Awaiting signature from the Chief Operating Officer."], ["Clause 7", "Auto-renews unless written notice is sent 30 days before term end."]], summary: "The agreement auto-renews at +9% unless notice is sent by October 19th.", related: [1] }),
      F("Employee_Onboarding_Guide.pdf", "People", "Approved", "People Ops", "Sep 29, 2026", "3.4 MB", { head: "Employee Onboarding Guide", sub: "Day 1 to day 30", fields: [["Sections", "9"], ["New hires", "4 this week"], ["Incomplete docs", "3"]], blocks: [["Week 1", "Accounts, security training, team introductions."]], summary: "The guide is current. Three new-hire documents are still incomplete.", related: [] }),
      F("Sales_Pipeline_October.xlsx", "Sales", "Updated", "Revenue Ops", "Oct 7, 2026", "310 KB", { head: "Sales Pipeline", sub: "October", fields: [["Open pipeline", "$2.1M"], ["Stalled deals", "3"], ["Stalled value", "$410k"]], table: { cols: ["Account", "Stage", "Value"], rows: [["Harbor Freight Co.", "Proposal", "$240k"], ["Alder Advisory", "Negotiation", "$180k"], ["Maple Health", "Stalled 16 days", "$150k"]] }, summary: "Three deals worth $410k have had no activity in over two weeks.", related: [0] }),
      F("Operations_KPI_Report.pdf", "Operations", "Approved", "Operations", "Oct 5, 2026", "2.2 MB", { head: "Operations KPI Report", sub: "Week 40", fields: [["Tasks on track", "91%"], ["Active projects", "12"], ["At risk", "2"]], blocks: [["At risk", "Platform migration and the partner portal."]], summary: "Operations are healthy overall. Two projects are at risk.", related: [0] }),
      F("Q4_Strategy_Draft.docx", "Strategy", "Needs Review", "Elena Ruiz", "Oct 6, 2026", "180 KB", { head: "Q4 Strategy Draft", sub: "Priorities and owners", fields: [["Priorities", "4"], ["Owners", "Assigned"], ["Status", "Draft"]], blocks: [["Priority 1", "Close the forecast gap without cutting customer-facing teams."], ["Priority 2", "Renegotiate the top three vendor contracts."]], summary: "The draft needs your review before it goes to the leadership team.", related: [1, 3] })
    ],
    workers: [["Meeting Assistant", "Turns meetings into notes and actions", "Watching"], ["Finance Monitor", "Watches forecast variance", "Processing"], ["Document Intake", "Files and tags new documents", "Idle"], ["Vendor Review", "Checks renewals and price rises", "Watching"], ["Executive Brief Generator", "Builds the daily leadership brief", "Idle"]],
    flows: [["Forecast variance alert", "Warns when a line drifts over target", 88], ["Vendor renewal watch", "Flags renewals 30 days out", 64], ["Meeting to actions", "Extracts owners and due dates", 76]],
    activity: [["MARVIN generated executive meeting summary", "20 min ago"], ["Forecast sheet updated", "1 h ago"], ["Vendor agreement uploaded", "Oct 3"], ["New employee onboarding started", "Mon"], ["Sales pipeline analyzed", "Mon"]],
    tasks: [["Sign the vendor agreement", "Today", 3], ["Review the Q4 forecast variance", "Today", 1], ["Prepare for the leadership meeting", "Today 3:00 PM", 2], ["Finish 3 onboarding documents", "Fri", 4]],
    chips: [["attention", "What needs executive attention?"], ["ops", "Summarize today's operations."], ["forecast", "What changed in the forecast?"], ["meeting", "Prepare me for the leadership meeting."]],
    marvin: {
      attention: ["Good morning. Three items need executive attention. The vendor agreement requires your signature and renews at a nine percent increase unless notice goes out by October 19th. The Q4 forecast is six percent over target. Your leadership briefing is due at 3 PM. I recommend signing the vendor agreement first.", [3, 1, 2]],
      ops: ["Operations look healthy. Twelve projects are active, ninety one percent of tasks are on track, and two projects are at risk: the platform migration and the partner portal. Four items are waiting for approval.", [6, 0]],
      forecast: ["The Q4 forecast moved from on target to six percent over. Three lines drive the change: cloud hosting is three hundred thousand over, contractors three hundred thousand over, and marketing software one hundred thousand over.", [1]],
      meeting: ["For the leadership meeting, lead with Q3 revenue of $4.8 million, three point one percent above plan. Then cover the forecast variance and the vendor renewal. Two action items from last week are overdue, so expect questions on budget cuts.", [0, 2, 1]]
    }
  };

  const realEstate = {
    id: "real-estate", route: "real-estate", icon: "🏠", name: "Real Estate", workspace: "Evergreen Realty Group", short: "Evergreen Realty",
    tint: "#19c6a0", user: { name: "Maya Ortiz", role: "Listing Broker", initials: "MO" },
    blurb: "Listings, buyers, transactions, inspections, disclosures and property operations.",
    summaryLine: "Here's what needs attention across Evergreen Realty Group today.",
    kpis: [["18", "Active Listings", "3 new this week"], ["6", "Pending Transactions", "2 closing soon"], ["$12.8M", "Active Pipeline", "Across 24 buyers"], ["3", "Closings This Week", "Thu and Fri"]],
    priority: [["HIGH", "742 Evergreen inspection response due", "Roof repair estimate", 1], ["HIGH", "Buyer offer expires today", "Johnson family, $402,000", 3], ["MEDIUM", "Disclosure packet missing signature", "Seller signature on page 4", 5], ["LOW", "Three listing photos awaiting approval", "Owner review", 7]],
    recommend: { title: "Answer the Johnson offer first", text: "It expires in six hours. The inspection found a roof issue worth about $7,800, which supports a counteroffer.", file: 3 },
    files: [
      F("742_Evergreen_Listing_Packet.pdf", "Listings", "Approved", "Maya Ortiz", "Oct 7, 2026", "9.8 MB", { head: "742 Evergreen Ave", sub: "Listing packet", fields: [["List price", "$415,000"], ["Size", "3 bed, 2 bath, 1,820 sq ft"], ["Days on market", "41"]], blocks: [["Highlights", "Renovated kitchen, fenced yard, two-car garage, near Maple Elementary."]], summary: "The listing is live at $415,000. Nearby sales support a higher price per square foot.", related: [2, 3] }),
      F("Property_Inspection_Report.pdf", "Inspections", "Flagged", "Harlan Inspections", "Oct 6, 2026", "5.1 MB", { head: "Property Inspection Report", sub: "742 Evergreen Ave", fields: [["Major findings", "1"], ["Minor findings", "9"], ["Repair estimate", "$7,800"]], blocks: [["Major", "Roof shingles at end of life on the north slope. Replacement recommended."], ["Response due", "Today, to the buyer's agent."]], summary: "One major finding: the roof, about $7,800. A response to the buyer's agent is due today.", related: [3, 0] }),
      F("Comparable_Sales.xlsx", "Research", "Updated", "Research Assistant", "Oct 7, 2026", "96 KB", { head: "Comparable Sales", sub: "Within half a mile", fields: [["Average", "$277 per sq ft"], ["Subject", "$228 per sq ft"], ["Sales used", "4"]], table: { cols: ["Address", "Sold", "Per sq ft"], rows: [["98 Alder St", "$498,000", "$278"], ["130 Alder St", "$512,000", "$277"], ["47 Birch Ln", "$489,000", "$278"], ["742 Evergreen (list)", "$415,000", "$228"]] }, summary: "Nearby homes sold for about $277 per square foot. 742 Evergreen is listed well under that.", related: [0, 3] }),
      F("Buyer_Offer_Johnson_Family.pdf", "Offers", "Needs Review", "Offer Assistant", "Oct 7, 2026", "380 KB", { head: "Buyer Offer", sub: "Johnson Family", fields: [["Offer", "$402,000"], ["Close", "21 days"], ["Expires", "Today 6:00 PM"]], blocks: [["Terms", "Pre-approved financing, inspection within 7 days, $5,000 earnest deposit."], ["Context", "Four percent below the nearby average. The roof finding gives room to counter."]], summary: "A solid offer that expires in six hours. A counter near $410,000 with a roof credit is reasonable.", related: [1, 2] }),
      F("Lease_Agreement.pdf", "Leases", "Signed", "Legal", "Sep 30, 2026", "720 KB", { head: "Lease Agreement", sub: "Guest unit, 742 Evergreen Ave", fields: [["Term", "12 months"], ["Rent", "$1,850 per month"], ["Signed", "Both parties"]], blocks: [["Notes", "Security deposit received. Move-in is scheduled for November 1."]], summary: "Signed by both parties. No action needed.", related: [] }),
      F("Disclosure_Packet.pdf", "Disclosures", "Pending", "Maya Ortiz", "Oct 5, 2026", "2.7 MB", { head: "Disclosure Packet", sub: "742 Evergreen Ave", fields: [["Pages", "12"], ["Signatures", "3 of 4"], ["Missing", "Seller, page 4"]], blocks: [["Missing signature", "The seller has not signed page 4. The packet cannot go to the buyer until it is signed."]], summary: "One signature is missing on page 4. The buyer cannot receive the packet until it is signed.", related: [3] }),
      F("Closing_Checklist.xlsx", "Closings", "Updated", "Transaction Coordinator", "Oct 7, 2026", "58 KB", { head: "Closing Checklist", sub: "Three closings this week", fields: [["Closings", "3"], ["Open items", "5"], ["Next", "Thu 10:00"]], table: { cols: ["Item", "Owner", "Status"], rows: [["Title search", "Title company", "Done"], ["Final walkthrough", "Agent", "Thu"], ["Funds confirmed", "Lender", "Pending"]] }, summary: "Three closings this week with five open items, mostly confirmations.", related: [] }),
      F("Property_Marketing_Plan.docx", "Marketing", "Approved", "Maya Ortiz", "Oct 2, 2026", "140 KB", { head: "Property Marketing Plan", sub: "742 Evergreen Ave", fields: [["Channels", "5"], ["Open house", "Sat 1:00 PM"], ["Photos", "3 awaiting approval"]], blocks: [["Plan", "Listing sites, email to the buyer list, neighborhood mailer and one open house."]], summary: "The plan is approved. Three new photos still need the owner's review.", related: [0] })
    ],
    workers: [["Listing Intake", "Builds listing packets from photos and notes", "Idle"], ["Transaction Monitor", "Tracks deadlines for every deal", "Watching"], ["Document Checker", "Finds missing signatures and pages", "Processing"], ["Buyer Follow-Up", "Drafts personal follow-ups", "Watching"], ["Market Analysis", "Builds comparable sales", "Idle"]],
    flows: [["Offer review", "Compares each offer to nearby sales", 82], ["Disclosure check", "Finds missing signatures before sending", 95], ["Buyer follow-up", "Drafts messages after every showing", 58]],
    activity: [["MARVIN detected missing disclosure signature", "15 min ago"], ["Inspection report uploaded", "Yesterday"], ["Comparable sales analysis generated", "1 h ago"], ["Buyer offer received", "2 h ago"], ["Closing checklist updated", "Today"]],
    tasks: [["Respond to the 742 Evergreen inspection", "Today", 1], ["Answer the Johnson family offer", "Today 6:00 PM", 3], ["Get the seller signature on page 4", "Today", 5], ["Approve 3 listing photos", "Fri", 7]],
    chips: [["attention", "Which deals need attention?"], ["evergreen", "What's blocking 742 Evergreen?"], ["documents", "Which documents are missing?"], ["closings", "Summarize today's closings."]],
    marvin: {
      attention: ["Good morning. Three deals need attention. The Johnson family offer on 742 Evergreen expires today at 6 PM. The inspection response is due, with a roof repair estimate of about $7,800. The disclosure packet is missing the seller's signature on page 4. I recommend answering the Johnson offer first.", [3, 1, 5]],
      evergreen: ["Two things are blocking 742 Evergreen. The inspection found a roof issue and the buyer's agent needs a response today. The disclosure packet is also missing one signature, so it cannot go to the buyer yet.", [1, 5]],
      documents: ["One document is incomplete. The disclosure packet for 742 Evergreen is missing the seller's signature on page 4. Everything else for this week's transactions is signed or on schedule.", [5]],
      closings: ["Three closings are scheduled this week, on Thursday and Friday. There are five open items, mostly confirmations. Funds from the lender are still pending for one of them.", [6]]
    }
  };

  window.NX = {
    industries: { construction, corporate, "real-estate": realEstate },
    order: ["construction", "corporate", "real-estate"],
    fallbackMarvin: "This is a simulated response. Try one of the suggested questions to see MARVIN answer.",
    keywords: {
      attention: /attention|urgent|priorit|first/i, holding: /holding|blocking|blocked|stuck/i, rfi: /rfi|042/i, invoices: /invoice|approve|approval/i,
      ops: /operation|today/i, forecast: /forecast|change/i, meeting: /meeting|prepare|brief/i,
      evergreen: /evergreen|742|blocking/i, documents: /document|missing|signature/i, closings: /closing/i
    },
    tutorial: [
      { t: "Welcome to NEXEN", d: "Your business operations, intelligence, automation and AI workers in one environment.", target: null },
      { t: "Your workspace", d: "Files, tasks, workflows and operational activity stay connected to the work they belong to.", target: "#dash" },
      { t: "Meet MARVIN", d: "Ask MARVIN questions using text or voice and surface the information that matters.", target: "#marvin-fab" },
      { t: "Automation + workers", d: "NEXEN can coordinate specialized tools and workers while keeping activity visible.", target: "#sec-workers" },
      { t: "You're ready", d: "Explore the workspace or switch industries to see how NEXEN adapts.", target: null }
    ],
    future: [
      { id: "ws", t: "NEXEN Spatial Workspace", d: "Immersive workspaces for viewing projects, files, automation and agents spatially.", badge: "CONCEPT PREVIEW", v: 0 },
      { id: "cc", t: "MARVIN Spatial Command Center", d: "Voice-first operational control inside an immersive workspace.", badge: "FUTURE DEVELOPMENT", v: 1 },
      { id: "ma", t: "Immersive Multi-Agent Operations", d: "Visualize human and AI work streams in a shared spatial operations environment.", badge: "RESEARCH / FUTURE DEVELOPMENT", v: 2 }
    ]
  };
})();
